### ISSUE TITLE
Demo does not show ably capabilites

### ISSUE THREAD

**Issue by richarddd** [ably/demo-typescript-jspm#2]
This demo just "demos" the connection capabilities. Its very convenient to see more examples.

Not even the  channel `subscribe` is demoed here

**Comment by SimonWoolf** [comment]
That's correct -- this isn't a demo of ably-js capabilities, rather it's a demo of how to get it actually up and running with TypeScript and JSPM.

For demos of ably-js capabilities, have a look through https://www.ably.io/tutorials (the tutorials all have full source code linked at each stage, and there are a selection of other demonstration apps linked at the bottom of the page, of which six out of eight use ably-js).
